//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SamuraiApp.Test.SamuraiServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SamuraiData", Namespace="http://schemas.datacontract.org/2004/07/SamuraiApp.Service")]
    [System.SerializableAttribute()]
    public partial class SamuraiData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PictureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SamuraiIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TownField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Picture {
            get {
                return this.PictureField;
            }
            set {
                if ((object.ReferenceEquals(this.PictureField, value) != true)) {
                    this.PictureField = value;
                    this.RaisePropertyChanged("Picture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SamuraiId {
            get {
                return this.SamuraiIdField;
            }
            set {
                if ((this.SamuraiIdField.Equals(value) != true)) {
                    this.SamuraiIdField = value;
                    this.RaisePropertyChanged("SamuraiId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Town {
            get {
                return this.TownField;
            }
            set {
                if ((object.ReferenceEquals(this.TownField, value) != true)) {
                    this.TownField = value;
                    this.RaisePropertyChanged("Town");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SamuraiServiceRef.ISamuraiService")]
    public interface ISamuraiService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISamuraiService/GetAllSamurais", ReplyAction="http://tempuri.org/ISamuraiService/GetAllSamuraisResponse")]
        SamuraiApp.Test.SamuraiServiceRef.SamuraiData[] GetAllSamurais();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISamuraiService/GetAllSamurais", ReplyAction="http://tempuri.org/ISamuraiService/GetAllSamuraisResponse")]
        System.Threading.Tasks.Task<SamuraiApp.Test.SamuraiServiceRef.SamuraiData[]> GetAllSamuraisAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISamuraiService/GetSamuraiById", ReplyAction="http://tempuri.org/ISamuraiService/GetSamuraiByIdResponse")]
        SamuraiApp.Test.SamuraiServiceRef.SamuraiData GetSamuraiById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISamuraiService/GetSamuraiById", ReplyAction="http://tempuri.org/ISamuraiService/GetSamuraiByIdResponse")]
        System.Threading.Tasks.Task<SamuraiApp.Test.SamuraiServiceRef.SamuraiData> GetSamuraiByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISamuraiService/UpdateSamurai", ReplyAction="http://tempuri.org/ISamuraiService/UpdateSamuraiResponse")]
        void UpdateSamurai(int id, string name, int age, string town);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISamuraiService/UpdateSamurai", ReplyAction="http://tempuri.org/ISamuraiService/UpdateSamuraiResponse")]
        System.Threading.Tasks.Task UpdateSamuraiAsync(int id, string name, int age, string town);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISamuraiServiceChannel : SamuraiApp.Test.SamuraiServiceRef.ISamuraiService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SamuraiServiceClient : System.ServiceModel.ClientBase<SamuraiApp.Test.SamuraiServiceRef.ISamuraiService>, SamuraiApp.Test.SamuraiServiceRef.ISamuraiService {
        
        public SamuraiServiceClient() {
        }
        
        public SamuraiServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SamuraiServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SamuraiServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SamuraiServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SamuraiApp.Test.SamuraiServiceRef.SamuraiData[] GetAllSamurais() {
            return base.Channel.GetAllSamurais();
        }
        
        public System.Threading.Tasks.Task<SamuraiApp.Test.SamuraiServiceRef.SamuraiData[]> GetAllSamuraisAsync() {
            return base.Channel.GetAllSamuraisAsync();
        }
        
        public SamuraiApp.Test.SamuraiServiceRef.SamuraiData GetSamuraiById(int id) {
            return base.Channel.GetSamuraiById(id);
        }
        
        public System.Threading.Tasks.Task<SamuraiApp.Test.SamuraiServiceRef.SamuraiData> GetSamuraiByIdAsync(int id) {
            return base.Channel.GetSamuraiByIdAsync(id);
        }
        
        public void UpdateSamurai(int id, string name, int age, string town) {
            base.Channel.UpdateSamurai(id, name, age, town);
        }
        
        public System.Threading.Tasks.Task UpdateSamuraiAsync(int id, string name, int age, string town) {
            return base.Channel.UpdateSamuraiAsync(id, name, age, town);
        }
    }
}
