//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SamuraiApp.Service
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SamuraiAppEntities : DbContext
    {
        public SamuraiAppEntities()
            : base("name=SamuraiAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__EFMigrationsHistory> C__EFMigrationsHistory { get; set; }
        public virtual DbSet<BattleEntity> BattleEntities { get; set; }
        public virtual DbSet<BattleSamuraiEntity> BattleSamuraiEntities { get; set; }
        public virtual DbSet<SamuraiEntity> SamuraiEntities { get; set; }
    }
}
