//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository2.BattleServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BattleData", Namespace="http://schemas.datacontract.org/2004/07/SamuraiApp.Service")]
    [System.SerializableAttribute()]
    public partial class BattleData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BattleIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BattleId {
            get {
                return this.BattleIdField;
            }
            set {
                if ((this.BattleIdField.Equals(value) != true)) {
                    this.BattleIdField = value;
                    this.RaisePropertyChanged("BattleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SamuraiData", Namespace="http://schemas.datacontract.org/2004/07/SamuraiApp.Service")]
    [System.SerializableAttribute()]
    public partial class SamuraiData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PictureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SamuraiIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TownField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Picture {
            get {
                return this.PictureField;
            }
            set {
                if ((object.ReferenceEquals(this.PictureField, value) != true)) {
                    this.PictureField = value;
                    this.RaisePropertyChanged("Picture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SamuraiId {
            get {
                return this.SamuraiIdField;
            }
            set {
                if ((this.SamuraiIdField.Equals(value) != true)) {
                    this.SamuraiIdField = value;
                    this.RaisePropertyChanged("SamuraiId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Town {
            get {
                return this.TownField;
            }
            set {
                if ((object.ReferenceEquals(this.TownField, value) != true)) {
                    this.TownField = value;
                    this.RaisePropertyChanged("Town");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BattleServiceRef.IBattleService")]
    public interface IBattleService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBattleService/GetAllBattles", ReplyAction="http://tempuri.org/IBattleService/GetAllBattlesResponse")]
        System.Collections.ObjectModel.Collection<Repository2.BattleServiceRef.BattleData> GetAllBattles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBattleService/GetAllBattles", ReplyAction="http://tempuri.org/IBattleService/GetAllBattlesResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.Collection<Repository2.BattleServiceRef.BattleData>> GetAllBattlesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBattleService/GetBattleById", ReplyAction="http://tempuri.org/IBattleService/GetBattleByIdResponse")]
        Repository2.BattleServiceRef.BattleData GetBattleById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBattleService/GetBattleById", ReplyAction="http://tempuri.org/IBattleService/GetBattleByIdResponse")]
        System.Threading.Tasks.Task<Repository2.BattleServiceRef.BattleData> GetBattleByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBattleService/UpdateBattle", ReplyAction="http://tempuri.org/IBattleService/UpdateBattleResponse")]
        void UpdateBattle(int id, string name, System.DateTime dateStarted, string town, string country);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBattleService/UpdateBattle", ReplyAction="http://tempuri.org/IBattleService/UpdateBattleResponse")]
        System.Threading.Tasks.Task UpdateBattleAsync(int id, string name, System.DateTime dateStarted, string town, string country);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBattleService/GetSamuraisInBattle", ReplyAction="http://tempuri.org/IBattleService/GetSamuraisInBattleResponse")]
        System.Collections.ObjectModel.Collection<Repository2.BattleServiceRef.SamuraiData> GetSamuraisInBattle(int battleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBattleService/GetSamuraisInBattle", ReplyAction="http://tempuri.org/IBattleService/GetSamuraisInBattleResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.Collection<Repository2.BattleServiceRef.SamuraiData>> GetSamuraisInBattleAsync(int battleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBattleService/AddSamuraiToBattle", ReplyAction="http://tempuri.org/IBattleService/AddSamuraiToBattleResponse")]
        void AddSamuraiToBattle(int samuraiId, int battleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBattleService/AddSamuraiToBattle", ReplyAction="http://tempuri.org/IBattleService/AddSamuraiToBattleResponse")]
        System.Threading.Tasks.Task AddSamuraiToBattleAsync(int samuraiId, int battleId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBattleServiceChannel : Repository2.BattleServiceRef.IBattleService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BattleServiceClient : System.ServiceModel.ClientBase<Repository2.BattleServiceRef.IBattleService>, Repository2.BattleServiceRef.IBattleService {
        
        public BattleServiceClient() {
        }
        
        public BattleServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BattleServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BattleServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BattleServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.ObjectModel.Collection<Repository2.BattleServiceRef.BattleData> GetAllBattles() {
            return base.Channel.GetAllBattles();
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.Collection<Repository2.BattleServiceRef.BattleData>> GetAllBattlesAsync() {
            return base.Channel.GetAllBattlesAsync();
        }
        
        public Repository2.BattleServiceRef.BattleData GetBattleById(int id) {
            return base.Channel.GetBattleById(id);
        }
        
        public System.Threading.Tasks.Task<Repository2.BattleServiceRef.BattleData> GetBattleByIdAsync(int id) {
            return base.Channel.GetBattleByIdAsync(id);
        }
        
        public void UpdateBattle(int id, string name, System.DateTime dateStarted, string town, string country) {
            base.Channel.UpdateBattle(id, name, dateStarted, town, country);
        }
        
        public System.Threading.Tasks.Task UpdateBattleAsync(int id, string name, System.DateTime dateStarted, string town, string country) {
            return base.Channel.UpdateBattleAsync(id, name, dateStarted, town, country);
        }
        
        public System.Collections.ObjectModel.Collection<Repository2.BattleServiceRef.SamuraiData> GetSamuraisInBattle(int battleId) {
            return base.Channel.GetSamuraisInBattle(battleId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.Collection<Repository2.BattleServiceRef.SamuraiData>> GetSamuraisInBattleAsync(int battleId) {
            return base.Channel.GetSamuraisInBattleAsync(battleId);
        }
        
        public void AddSamuraiToBattle(int samuraiId, int battleId) {
            base.Channel.AddSamuraiToBattle(samuraiId, battleId);
        }
        
        public System.Threading.Tasks.Task AddSamuraiToBattleAsync(int samuraiId, int battleId) {
            return base.Channel.AddSamuraiToBattleAsync(samuraiId, battleId);
        }
    }
}
